#! /bin/bash

# Read paths from config file
source <(grep = ./src/config.ini)

echo "Installing Nautilus extension to $extpath"

# Create Directory if necessary
mkdir -p $extpath
mkdir -p $srcpath

# Copy files
cp -i ./nautilus-latex.py $extpath
cp -r -i ./src $srcpath

# Chmods of copied files
chmod 755 $extpath/nautilus-latex.py
chmod -R 755 $srcpath

# Insert SRC path to python script
sed -i "21isrc_path = '$srcpath'" $extpath/nautilus-latex.py

echo "Done"