#! /bin/bash

# Read paths from config file
source <(grep = ./src/config.ini)

echo "Removing Nautilus extension"

rm $extpath/nautilus-latex.py
rm $extpath/nautilus-latex.pyc >/dev/null 2>/dev/null
rm -r $srcpath

echo "Done"